### ISSUE TITLE
Large NoData Areas in TIFF Files Downloaded from OpenEO in Python

### ISSUE THREAD

**Issue by paulasanchezgt** [Open-EO/openeo-python-client#658] opened 2024-11-13 11:26 UTC
Hello everyone,

I've been downloading TIFF files using OpenEO in Python, and although the files seem correctly formatted, I'm encountering a major issue: many pixels show as NoData. Depending on the date I select, I often get only a small square of actual data, while the rest of the spatial extent has NoData.

Interestingly, if I manually download the same area and time range from the Copernicus Browser, I get data across the entire spatial extent.

Does anyone know why this discrepancy is happening between OpenEO and the Copernicus Browser? Is there a specific setting in OpenEO that might be causing this, or a configuration issue in Python?

**Comment by bossie** [comment] 2024-11-13 12:28
Duplicate of #659.

**Closed as completed by bossie** 2024-11-13 12:28 UTC
