### ISSUE TITLE
Improved handling temporal extents

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-python-client#349] opened 2022-12-08 14:19 UTC
background story references: https://github.com/Open-EO/openeo-geopyspark-driver/issues/34, https://github.com/Open-EO/openeo-processes/issues/331, https://github.com/Open-EO/openeo-processes/pull/394

Regarding temporal extents, there is a bit of (long standing) conflict between the current VITO back-end implementation (end timestamp is inclusive) and the official openEO spec (end timestamp exclusive). 
The VITO back-end will at some point probably fix this by adapting the spec way, but this could potentially break some existing use cases, examples/demos, etc..

For example, a common usage pattern in the wild for (VITO) users and use cases: user knows that there is an  observation on certain day, e.g. "2022-01-02", and specifies temporal extent like `["2022-01-02", "2022-01-02"]`.  This is strictly per-spec an empty interval and with  https://github.com/Open-EO/openeo-processes/pull/394  even invalid (throw error).

We should think of some ways to catch these problems at the level of the python client, e.g.
- warn  when client detects that start==end
- fix the end date in some way (e.g. add 24 hours or something)
- allow the user to specify a single date string, e.g. "2022-01-02", and expand that under the hood automatically to the valid corresponding extent `["2022-01-02", "2022-01-03"]`
- ...

**Comment by jdries** [comment] 2023-09-29 13:40
@soxofaan  @JohanKJSchreurs  isn't this a duplicate of something that we fixed?

**Comment by soxofaan** [comment] 2023-09-29 15:36
> allow the user to specify a single date string, e.g. "2022-01-02", and expand that under the hood automatically to the valid corresponding extent ["2022-01-02", "2022-01-03"]

this was indeed implemented under #421/#468

**Comment by soxofaan** [comment] 2023-09-29 15:39
Warning about and/or autofixing a temporal extent with identical dates like `["2022-01-02", "2022-01-02"]` could still be considered as an extra feature, but I'm not sure if that is still worth it

**Comment by jdries** [comment] 2023-10-03 05:31
let's not do the warning for now

**Closed by jdries** 2023-10-03 05:31 UTC
Labels: feature request, usability, api compliancy
