### ISSUE TITLE
No metadata for datacube loaded with `load_stac`

### ISSUE THREAD

**Issue by VincentVerelst** [Open-EO/openeo-python-client#527] opened 2024-01-15 11:04 UTC
Datacubes that are loaded from a STAC catalog using `load_stac` don't contain any metadata.

**Comment by soxofaan** [comment] 2024-01-15 12:59
related to https://github.com/Open-EO/openeo-python-client/issues/464 and https://github.com/Open-EO/openeo-python-client/issues/425

**Comment by jdries** [comment] 2024-01-16 07:27
This is also a duplicate of:
https://github.com/Open-EO/openeo-python-client/issues/368
We'll probably just want to clearly deprecate load_result, so that we only have to fix this one.

**Comment by soxofaan** [comment] 2024-01-16 09:10
FYI: `load_result` is a non-experimental process in openeo-processes 1.0.0 (it moved to "proposals" in 1.1.0), so strictly speaking we can not easily deprecate it in general. But I agree that we probably should not bother (bug)fixing it.

**Comment by VincentVerelst** [comment] 2024-03-11 14:21
TODO: add unit testing

**Closed** 2024-03-25 16:47 UTC
