### ISSUE TITLE
Process graph output from python client different from web editor

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-python-client#209] opened 2021-05-13 07:49 UTC
I'v noticed that if I type datacube.graph using the python client, the process graph has a different format compared to the one visible using the web editor. Basically, it is missing the "process graph" root node.

Python Client version:

```
{'loadcollection1': {'process_id': 'load_collection',
  'arguments': {'bands': ['B02_10m', 'B03_10m', 'B04_10m'],
   'id': 'S2_L2A_T32TPS',
   'spatial_extent': {'west': 11.280484,
    'east': 11.397882,
    'south': 46.456655,
    'north': 46.519532},
   'temporal_extent': ['2018-06-06', '2018-06-08']}},
 'saveresult1': {'process_id': 'save_result',
  'arguments': {'data': {'from_node': 'loadcollection1'},
   'format': 'GTiff',
   'options': {}},
  'result': True}}
```

Web Editor version:
```
{
  "process_graph": {
    "1": {
      "process_id": "load_collection",
      "arguments": {
        "id": "S2_L2A_T32TPS",
        "spatial_extent": {
          "west": 11.29669189453125,
          "south": 46.460565545785386,
          "east": 11.388015747070312,
          "north": 46.52343797415179
        },
        "temporal_extent": [
          "2018-08-01T00:00:00Z",
          "2018-08-30T23:59:59Z"
        ],
        "bands": [
          "B02_10m",
          "B03_10m",
          "B04_10m"
        ],
        "properties": {}
      }
    },
    "4": {
      "process_id": "save_result",
      "arguments": {
        "data": {
          "from_node": "1"
        },
        "format": "GTIFF"
      },
      "result": true
    }
  }
}
```

**Comment by clausmichele** [comment] 2021-05-14 13:47
The same behavior is present in the R client https://github.com/Open-EO/openeo-r-client/issues/54

**Comment by m-mohr** [comment] 2021-05-14 14:24
This is basically the same issue as described here: https://github.com/Open-EO/openeo-python-client/issues/155
Seems it wasn't fully resolved yet...

**Comment by jdries** [comment] 2021-05-17 06:49
The python client is fully 1.0 compliant. You can use:
openeo.rest.datacube.DataCube.to_json
if you want a json representation that looks like the one from the web editor.
For backwards compatibility, the public methods and properties have to remain the same.

**Comment by m-mohr** [comment] 2021-05-17 07:53
But then the graph method could/should be marked as deprecated and point to to_json, right? That would guide users to the method that is actually useful for them.

**Comment by soxofaan** [comment] 2021-05-17 09:44
Indeed, the `.graph` property is not really recommended for general use. It is manly a left-over from the 0.4 times that was heavily used in unit tests and with the addition of  1.0 support we kept it to make sure we could re-use the existing tests as much as possible.

Overall, the current state of DataCube is a bit messy in this area: we have these three properties/methods  `.graph`, `.flat_graph()` and `flatten()`, and they all do the same: return a "flat graph" representation of the underlying process graph, but in 0.4 style (without "process_graph" level). 
However, a normal user should not have to use any of these in the first place (which is why they are not optimally documented/deprecated yet). At most, a normal user could want a JSON dump of the process graph, which is covered by the `to_json()` method (including the "process_graph" level), as mentioned by @jdries .

So I am curious @clausmichele  why are you using `.graph` actually? Do you have a real use case where you want to manipulate the "flat" graph before sending it to a backend in some way?

**Comment by clausmichele** [comment] 2021-05-17 09:53
I was trying to use the `.graph` just for testing, trying to get the same graph with a custom process both in the Web Editor and in the Python Client. I didn't know about the other method, so I will use that one and continue with my tests!

**Comment by soxofaan** [comment] 2022-08-11 14:29
Closing this as duplicate of #155 to keep discussion more focussed

**Closed by soxofaan** 2022-08-11 14:29 UTC
Labels: user interface
